title: Dissuptyper
description: R source code for performing disease subtyping through a systems biology approach for unsupervised clustering of high-dimensional data
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
